name: "Setup Java"
description: "Setup Java JDK and Gradle cache"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'
