inputs:
  command:
runs:
  using: "composite"
  steps:
    - name: Run Tests
      run: ${{ inputs.command }}

    - name: Upload Unit Test Results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: Unit Test Results (Python ${{ matrix.python-version }})
        path: pytest.xml