name: Generate OpenApi Spec

on:
  push:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  GenerateOAS:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Generate YAML spec
        run: |
          ./gradlew resolve
          ./gradlew mergeOpenApiFiles

      - name: Check OpenAPI files match code
        run: git diff --exit-code
