name: Integration Tests

on: [ push, pull_request ]

jobs:

  Integration-Test:
    runs-on: ubuntu-latest

    services:
      azurite:
        image: mcr.microsoft.com/azure-storage/azurite
        ports:
          - 10000:10000
        env:
          AZURITE_ACCOUNTS: account1:key1;account2:key2
      minio:
        image: bitnami/minio:latest
        ports:
          - 9000:9000
        env:
          MINIO_ACCESS_KEY: root
          MINIO_SECRET_KEY: password
      omejdn:
        image: ghcr.io/fraunhofer-aisec/omejdn-server:1.2.1
        ports:
          - 4567:4567
        volumes:
          - ${{ github.workspace }}/extensions/iam/daps/src/test/resources/config:/opt/config
          - ${{ github.workspace }}/extensions/iam/daps/src/test/resources/keys:/opt/keys

    steps:
      - name: reset permissions to permit checkout (because the omejdn volumes)
        run: sudo chown -R $USER:$USER ${{ github.workspace }}

      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: Integration Tests
        run: ./gradlew clean check -DincludeTags="IntegrationTest" -DexcludeTags="azure-cosmos-db,FileTransferAsClient"

  Azure-CosmosDB-Integration-Test:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup Gradle cache
        uses: gradle/gradle-build-action@v2

      # Cosmos DB Emulator is preinstalled on GitHub Actions workers
      - name: Launch Cosmos DB Emulator
        run: |
          Import-Module "$env:ProgramFiles\Azure Cosmos DB Emulator\PSModules\Microsoft.Azure.CosmosDB.Emulator"
          Start-CosmosDbEmulator -Timeout 1200

      - name: Azure CosmosDB Tests
        run: ./gradlew check -DincludeTags="azure-cosmos-db"

