name: Performance Tests

on: [ push, pull_request ]

jobs:

  Performance-Test:
    runs-on: ubuntu-latest

    env:
      REPEAT: 1
      AT_ONCE_USERS: 1
      MAX_RESPONSE_TIME: 5000
      SUCCESS_PERCENTAGE: 100.0

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Performance Tests
        run: ./gradlew test -DincludeTags="PerformanceTest"
