name: Test Code (Style, Tests)

on:
  push:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Checkstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # lets run Checkstyle explicitly (as opposed to within gradle) due to better reporting capabilities
      - name: Run Checkstyle
        uses: nikitasavinov/checkstyle-action@0.4.0
        with:
          checkstyle_config: resources/edc-checkstyle-config.xml
          level: error
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tool_name: 'checkstyle'
          checkstyle_version: '9.0'
          reporter: 'github-check'
          filter_mode: 'nofilter'
